language: java

jdk:
  - oraclejdk8

env:
  - VERSION=xxx

services:
  - postgresql

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_script:
  - psql -c 'drop database momowarstest;' -U postgres
  - psql -c 'create database momowarstest;' -U postgres

script:
  - mvn clean package test