language: java

jdk:
  - oraclejdk8

env:
  global:
    - PORT=5000
    - JDBC_DATABASE_URL=jdbc:postgresql://localhost:5432/momowarstest?user=postgres
    - CONNECTION_POOL_SIZE=3

services:
  - postgresql

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_script:
  - psql -c "create database momowarstest;" -U postgres

script:
  - mvn clean test package