DO $$
BEGIN

	IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'movement_type') THEN
		CREATE TYPE MOVEMENT_TYPE AS ENUM ('NONE', 'UP_LEFT', 'UP', 'UP_RIGHT', 'DOWN_RIGHT', 'DOWN', 'DOWN_LEFT');
	END IF;

END $$;