DO $$
BEGIN

	IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unit_type') THEN
		CREATE TYPE UNIT_TYPE AS ENUM ('SQUAD', 'MORTAR', 'HUMVEE', 'LIGHT_TANK', 'HEAVY_TANK', 'HELICOPTER');
	END IF;
    
END $$;