CREATE TABLE IF NOT EXISTS account (
	id SERIAL PRIMARY KEY,
	email VARCHAR(50) UNIQUE NOT NULL,
	nickname VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	session VARCHAR(128) UNIQUE NOT NULL);