CREATE TABLE player (
	id SERIAL PRIMARY KEY,
	match INTEGER NOT NULL REFERENCES match(id),
	account INTEGER NOT NULL REFERENCES account(id),
	resources INTEGER NOT NULL CHECK (resources >= 0),
	status PLAYER_STATUS NOT NULL);